---
- hosts: mgmt
  vars: 
    microk8s_plugins:
      dns: true
      ingress: true
      cert-manager: true
      hostpath-storage: true

    # make sure this cert file is a root or intermediate CA that can sign csrs for the ingress paths you're planning 
    # to use in your cluster.
    cert_manager_tls_cert_file: "/home/alex/DARE-SeRP-Dev-Deployment/ansible/microk8s_example/certs/cert.crt"
    cert_manager_tls_key_file: "/home/alex/DARE-SeRP-Dev-Deployment/ansible/microk8s_example/certs/cert.key"

    k3s_metallb_addresses: 
      - 192.168.69.210/29

    k3s_deploy_rookceph: false
    k3s_deploy_metallb: true
    k3s_deploy_opa: false
    k3s_deploy_argo: true
    k3s_deploy_postop: false
    k3s_deploy_nexus: true
    k3s_populate_nexus: false
    k3s_deploy_minioop: false
    k3s_deploy_vault: true
    k3s_deploy_extra_manifests: true

    helm_source_values_dir: "/home/alex/DARE-SeRP-Dev-Deployment/ansible/microk8s_example/helm_values/mgmt/"
    teleport_chart_directory: "../../charts/deployment"
    extra_manifests_folder: '/home/alex/DARE-SeRP-Dev-Deployment/ansible/microk8s_example/extra_manifests/mgmt'
    vault_config_output_folder: '/home/alex/DARE-SeRP-Dev-Deployment/ansible/output/vault'

    harbor_dare_user: ""
    harbor_dare_pass: ""

    k3s_helm_install:
      metallb:
        install_name: 'metallb'
        install_namespace: 'networking'
        chart_name: 'metallb'
        chart_version: '4.4.2'
        repo_address: 'https://charts.bitnami.com/bitnami'
        install_values: ''
      argocd:
        install_name: 'argocd'
        install_namespace: 'argocd'
        chart_name: 'argo-cd'
        chart_version: '5.39.0'
        repo_address: 'https://argoproj.github.io/argo-helm'
        install_values: 'argo.yaml'
      nexus:
        install_name: 'nexus'
        install_namespace: 'nexus'
        chart_name: 'nexus-repository-manager'
        chart_version: '58.1.0'
        repo_address: 'https://sonatype.github.io/helm3-charts/'
        install_values: 'nexus.yaml'
      vault:
        install_name: 'vault'
        install_namespace: 'vault'
        chart_name: 'vault'
        chart_version: '0.24.1'
        repo_address: 'https://helm.releases.hashicorp.com'
        install_values: 'vault.yaml'

  roles:
    - dare.common.microk8s
    - dare.common.helm_install