# This section includes base Calico installation configuration.
# For more information, see: https://docs.projectcalico.org/v3.20/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  nonPrivileged: Enabled
  # Configures Calico networking.
  calicoNetwork:
    containerIPForwarding: Enabled
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: {{ k3s_server.cluster-cidr }}
      encapsulation: IPIP
      natOutgoing: Enabled
      nodeSelector: all()
  controlPlaneTolerations:
    - key: "node-role.kubernetes.io/control-plane"
      effect: NoSchedule

---
# This section configures the Calico API server.
# For more information, see: https://docs.projectcalico.org/v3.20/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
spec: {}