defaultVaultConnection:
  enabled: true
  # as this is being deployed on the same cluster, we can use internal addressing for vault
  address: "http://vault-active.vault.svc.cluster.local:8200"

defaultAuthMethod:
  enabled: true
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: "work-dare"
    serviceAccount: default