appTeleport:
  enabled: true
  address: https://kubernetes.default.svc
  namespace: serp-sail-teleport
  argocd:
    namespace: hiru-mgmt-argocd
    project: serp-sail-teleport

  source:
    repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
    chart: teleport
    targetRevision: 1.4.2

  values:
    global:
      namespacePrefix: dare
      application:
        address: https://kubernetes.default.svc
        argocd:
          namespace: serp-sail-teleport
          project: serp-sail-teleport
      management:
        address: https://kubernetes.default.svc
        argocd:
          namespace: serp-sail-teleport
          project: serp-sail-teleport
      monitoring:
        address: https://kubernetes.default.svc
        argocd:
          namespace: serp-sail-teleport
          project: serp-sail-teleport

    appGuacamole:
      enabled: false
      namespace: guacamole
      source:
        repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
        chart: guacamole
        targetRevision: 1.0.2

    appJupyter:
      enabled: true
      namespace: jupyterhub
      source:
        repoURL: https://hub.jupyter.org/helm-chart/
        chart: jupyterhub
        targetRevision: 3.0.2
      values:
        singleuser:
          lifecycleHooks:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    /usr/local/bin/start-notebook.d/session_startup.sh
          networkPolicy:
            enabled: false
          defaultUrl: "/lab"
          extraEnv:
            JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
          profileList:
          - display_name: "basic image"
            kubespawner_override:
              image: "harbor.ukserp.ac.uk/dare/jupyter:1.1.0"

        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/rewrite-target: /
            kubernetes.io/ingress.class: "nginx-hiru"
            cert-manager.io/cluster-issuer: "ca-issuer"
          hosts:
            - jupyterhub.dare.sail.dk.serp.ac.uk
          tls:
            - hosts:
              - jupyterhub.dare.sail.dk.serp.ac.uk
              secretName: jupyterhub-chi-tls


    appTrino:
      enabled: true
      namespace: trino
      source:
        repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
        chart: trino
        targetRevision: 1.1.1
      values:
        image:
          repository: harbor.ukserp.ac.uk/dare/trino
          tag: "1.2.0"

        server:
          workers: 2

        additionalCatalogs:
          minio: |
            connector.name = hive
            hive.metastore.uri = thrift://hive-metastore:9083
            hive.metastore.thrift.delete-files-on-drop=true
            hive.s3.path-style-access=true
            hive.s3.endpoint=http://minio.dare-minio-tenant.svc.cluster.local:80
            hive.s3.aws-access-key=06LVN2MwcfLzsFr7BZ
            hive.s3.aws-secret-key=SrOMOsnLa8gTHWvEUk3hNxZP
            hive.non-managed-table-writes-enabled=true
            hive.s3select-pushdown.enabled=true
            hive.storage-format=ORC
            hive.allow-drop-table=true
          iceberg: |
            connector.name = hive
            hive.metastore.uri = thrift://hive-metastore:9083
            hive.metastore.thrift.delete-files-on-drop=true
            hive.s3.path-style-access=true
            hive.s3.endpoint=http://minio.dare-minio-tenant.svc.cluster.local:80
            hive.s3.aws-access-key=06LVN2MwcfLzsFr7BZ
            hive.s3.aws-secret-key=SrOMOsnLa8gTHWvEUk3hNxZP
            hive.non-managed-table-writes-enabled=true
            hive.s3select-pushdown.enabled=true
            hive.storage-format=ORC
            hive.allow-drop-table=true
          remotetrino: |
            connector.name = trino
            connection-url=jdbc:trino://trino.feasability.sail.pk.serp.ac.uk/tpcds/sf3000
            connection-user=alexandra.lee
            connection-password=${ENV:remotetrinopassword}
            join-pushdown.enabled=true
            join-pushdown.strategy=EAGER
            unsupported-type-handling=CONVERT_TO_VARCHAR

        ingress:
          enabled: true
          className: "nginx-hiru"
          host: "trino.dare.sail.dk.serp.ac.uk"

        metrics:
          enabled: false

        ranger:
          enabled: false

    appHive:
      enabled: true
      namespace: trino
      source:
        repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
        chart: hive
        targetRevision: 1.2.0
      values:
        image:
          name: harbor.chi.swan.ac.uk/trino/hive-metastore
          tag: "main-0e0bfa97"

        minio:
          accessKey:
          secretKey:

        mysql:
          architecture: replication
          auth:
            rootPassword: 'P4ssW0rd!1'
            createDatabase: true
            database: metastore_db
            username: hive
            password: 'H1v3P4ssW0rd!1'
            replicationPassword: 'R3pl1c4t1onP4ssW0rd!1'

          secondary:
            replicaCount: 1

          metrics:
            enabled: false

        env: 
          - name: makeit
            value: work

    appMinioTenant:
      enabled: true
      namespace: minio-tenant
      source:
        repoURL: https://operator.min.io/
        chart: tenant
        targetRevision: 5.0.6
      values:
        secrets:
          name: tmp-minio-env-config
          accessKey: "06LVN2MwcfLzsFr7BZ"
          secretKey: "SrOMOsnLa8gTHWvEUk3hNxZP"

        tenant:
          name: dare-teleport
          configuration:
            name: tmp-minio-env-config

          pools:
            - servers: 2
              name: pool-0
              volumesPerServer: 2
              size: 50Gi 
              storageClassName: ceph-block

          metrics:
            enabled: false

          certificate:
            requestAutoCert: false

          prometheusOperator: false

        ingress:
          api:
            enabled: true
            ingressClassName: "nginx-hiru"
            annotations: 
              cert-manager.io/cluster-issuer: ca-issuer
              nginx.ingress.kubernetes.io/proxy-body-size: 1000m
            host: minio-api.dare.sail.dk.serp.ac.uk
            path: /
            pathType: Prefix

          console:
            enabled: true
            ingressClassName: "nginx-hiru"
            annotations: 
              cert-manager.io/cluster-issuer: ca-issuer
              nginx.ingress.kubernetes.io/proxy-body-size: 1000m
            host: minio.dare.sail.dk.serp.ac.uk
            path: /
            pathType: Prefix

    appVault:
      enabled: false
      namespace: vault
      source:
        repoURL: https://helm.releases.hashicorp.com
        chart: vault
        targetRevision: 0.24.1

    appOpa:
      enabled: false
      namespace: opa
      source:
        repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
        chart: opa
        targetRevision: 1.0.0

    appControl:
      enabled: false

    appKeycloak:
      enabled: false
      namespace: keycloak
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: keycloak
        targetRevision: 15.1.6

    appPromStack:
      enabled: false

    appLoki:
      enabled: false