
appTeleport:
  enabled: true
  address: https://kubernetes.default.svc
  namespace: argocd
  argocd:
    namespace: argocd
    project: default

  source:
    repoURL: harbor.ukserp.ac.uk/dare/chart
    chart: teleport
    # renovate: datasource=docker depName=dare/chart/teleport registryUrl=https://harbor.ukserp.ac.uk
    targetRevision: 1.4.2

  # values:

  #   global:
  #     namespacePrefix: dare
  #     application:
  #       address: https://192.168.69.202:16443
  #       argocd:
  #         namespace: argocd
  #         project: default
  #     management:
  #       address: https://kubernetes.default.svc
  #       argocd:
  #         namespace: argocd
  #         project: default
  #     monitoring:
  #       address: https://192.168.69.201:16443
  #       argocd:
  #         namespace: argocd
  #         project: default
